// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: liquiditaet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from liquiditaet.proto</summary>
public static partial class LiquiditaetReflection {

  #region Descriptor
  /// <summary>File descriptor for liquiditaet.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LiquiditaetReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFsaXF1aWRpdGFldC5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFt",
          "cC5wcm90byJkCg5SZXFfTGlxdWlkcGxhbhIpCgViZWdpbhgBIAEoCzIaLmdv",
          "b2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASJwoDZW5kGAIgASgLMhouZ29vZ2xl",
          "LnByb3RvYnVmLlRpbWVzdGFtcCI2Cg5SZXNfTGlxdWlkcGxhbiIkCghFU3Vj",
          "Y2VlZBILCgdTVUNDRUVEEAASCwoHRkFJTFVSRRABIiIKD0luZm9fTGlxdWlk",
          "UGxhbhIPCgdVTkNQYXRoGAEgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Req_Liquidplan), global::Req_Liquidplan.Parser, new[]{ "Begin", "End" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Res_Liquidplan), global::Res_Liquidplan.Parser, null, null, new[]{ typeof(global::Res_Liquidplan.Types.ESucceed) }, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Info_LiquidPlan), global::Info_LiquidPlan.Parser, new[]{ "UNCPath" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Req_Liquidplan : pb::IMessage<Req_Liquidplan> {
  private static readonly pb::MessageParser<Req_Liquidplan> _parser = new pb::MessageParser<Req_Liquidplan>(() => new Req_Liquidplan());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Req_Liquidplan> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LiquiditaetReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Req_Liquidplan() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Req_Liquidplan(Req_Liquidplan other) : this() {
    begin_ = other.begin_ != null ? other.begin_.Clone() : null;
    end_ = other.end_ != null ? other.end_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Req_Liquidplan Clone() {
    return new Req_Liquidplan(this);
  }

  /// <summary>Field number for the "begin" field.</summary>
  public const int BeginFieldNumber = 1;
  private global::Google.Protobuf.WellKnownTypes.Timestamp begin_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Begin {
    get { return begin_; }
    set {
      begin_ = value;
    }
  }

  /// <summary>Field number for the "end" field.</summary>
  public const int EndFieldNumber = 2;
  private global::Google.Protobuf.WellKnownTypes.Timestamp end_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp End {
    get { return end_; }
    set {
      end_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Req_Liquidplan);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Req_Liquidplan other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Begin, other.Begin)) return false;
    if (!object.Equals(End, other.End)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (begin_ != null) hash ^= Begin.GetHashCode();
    if (end_ != null) hash ^= End.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (begin_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Begin);
    }
    if (end_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(End);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (begin_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Begin);
    }
    if (end_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(End);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Req_Liquidplan other) {
    if (other == null) {
      return;
    }
    if (other.begin_ != null) {
      if (begin_ == null) {
        Begin = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      Begin.MergeFrom(other.Begin);
    }
    if (other.end_ != null) {
      if (end_ == null) {
        End = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      End.MergeFrom(other.End);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (begin_ == null) {
            Begin = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Begin);
          break;
        }
        case 18: {
          if (end_ == null) {
            End = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(End);
          break;
        }
      }
    }
  }

}

public sealed partial class Res_Liquidplan : pb::IMessage<Res_Liquidplan> {
  private static readonly pb::MessageParser<Res_Liquidplan> _parser = new pb::MessageParser<Res_Liquidplan>(() => new Res_Liquidplan());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Res_Liquidplan> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LiquiditaetReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Res_Liquidplan() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Res_Liquidplan(Res_Liquidplan other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Res_Liquidplan Clone() {
    return new Res_Liquidplan(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Res_Liquidplan);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Res_Liquidplan other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Res_Liquidplan other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the Res_Liquidplan message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum ESucceed {
      [pbr::OriginalName("SUCCEED")] Succeed = 0,
      [pbr::OriginalName("FAILURE")] Failure = 1,
    }

  }
  #endregion

}

public sealed partial class Info_LiquidPlan : pb::IMessage<Info_LiquidPlan> {
  private static readonly pb::MessageParser<Info_LiquidPlan> _parser = new pb::MessageParser<Info_LiquidPlan>(() => new Info_LiquidPlan());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Info_LiquidPlan> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LiquiditaetReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Info_LiquidPlan() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Info_LiquidPlan(Info_LiquidPlan other) : this() {
    uNCPath_ = other.uNCPath_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Info_LiquidPlan Clone() {
    return new Info_LiquidPlan(this);
  }

  /// <summary>Field number for the "UNCPath" field.</summary>
  public const int UNCPathFieldNumber = 1;
  private string uNCPath_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UNCPath {
    get { return uNCPath_; }
    set {
      uNCPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Info_LiquidPlan);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Info_LiquidPlan other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UNCPath != other.UNCPath) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (UNCPath.Length != 0) hash ^= UNCPath.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (UNCPath.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UNCPath);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (UNCPath.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UNCPath);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Info_LiquidPlan other) {
    if (other == null) {
      return;
    }
    if (other.UNCPath.Length != 0) {
      UNCPath = other.UNCPath;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UNCPath = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
